import {
  BedDouble,
  Users,
  Receipt,
  Package,
  Plus,
  Search,
  ArrowUpLeft,
  ArrowDownLeft,
  ArrowRight,
  ChevronLeft,
  ChevronRight,
  X,
  Check,
  LogOut,
  Settings,
  ShieldCheck,
  HeartPulse,
  Wallet,
  TrendingUp,
  ArrowLeftRight,
  Printer,
  MoreHorizontal,
  CheckCircle2,
  AlertCircle,
  RefreshCw,
  Building2,
  Clock,
  Minus,
  Archive,
  Trash2,
} from 'lucide-react';
const icons = {
  bed: BedDouble,
  patients: Users,
  bills: Receipt,
  inventory: Package,
  plus: Plus,
  search: Search,
  up: ArrowUpLeft,
  down: ArrowDownLeft,
  back: ArrowRight,
  left: ChevronLeft,
  right: ChevronRight,
  close: X,
  check: Check,
  logout: LogOut,
  settings: Settings,
  shield: ShieldCheck,
  heart: HeartPulse,
  wallet: Wallet,
  trend: TrendingUp,
  transfer: ArrowLeftRight,
  print: Printer,
  more: MoreHorizontal,
  success: CheckCircle2,
  alert: AlertCircle,
  refresh: RefreshCw,
  building: Building2,
  clock: Clock,
  minus: Minus,
  archive: Archive,
  trash: Trash2,
};
export function Icon({ name, size = 20 }: { name: keyof typeof icons; size?: number }) {
  const Component = icons[name];
  return <Component size={size} strokeWidth={1.7} aria-hidden="true" />;
}
export type IconName = keyof typeof icons;
